
language: cpp
sudo: require

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0

before_install:
 # Install a supported cmake version (>= 3.5)
 - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-rc1-Linux-x86_64.sh 
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

install:
  - cmake -H. -Bbuild
  - cmake --build build
  - sudo cmake --build build --target install

script:
  - cmake -Htests -Bbuild/test  
  - cmake --build build/test
  - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build/test --target test
 